### ISSUE TITLE
GraphQL invalid credentials 

### ISSUE THREAD

**Issue by sunilit42** [bigcommerce/b2b-buyer-portal#10]
I m trying to setup locally b2b portal.

I m getting below error msg :-  
{"errors":[{"message":"GraphQL invalid credentials. String is not a JWT"}]}

For temp fix

`  graphqlBC: function post<T>(data: T): Promise<any> {
    console.log(store.getState())
    let { bcGraphqlToken } = store.getState().company.tokens
    bcGraphqlToken ='created token and added here';
    const config = {
      Authorization: `Bearer  ${bcGraphqlToken}`,
    }
    return graphqlRequest(RequestType.BCGraphql, data, config)
  },`

After adding that graphql calling but getting below error 
`'Origin' header invalid: The 'Origin' request header value did not match the allowed origin set in the JWT auth token. Please generate a token that is valid for this origin`

I created that GraphQL using http://localhost:3000/ as domain but still getting error

Please help us to setup locally.

Thanks

**Comment by bc-victor** [comment]
@sunilit42 Hello, a couple asks:

- Could you attach screenshots or refer to a fork? Environment variables also help 
- Are you working on top of a stencil or headless channel?

Regards

**Comment by jp06** [comment]
I am also getting the issue in a local Stencil theme setup. Not sure if I messed up something during setup, but it seems that it's passing an undefined GraphQL token in the request.

In the meanwhile, the workaround I did is to use the storefront API token provided during page load. You can do it somewhere above in the layout template files (`base.html`, and maybe `empty.html` also if used in checkout page):
```handlebars
<script>
    window.STOREFRONT_GRAPHQL_API_TOKEN = '{{{ settings.storefront_api.token }}}'
</script>
```

And then in the `b3Fetch.ts` file in Buyer Portal code, I updated to this for now:
```typescript
const B3Request = {
  /* ... */
  graphqlBC: function post<T>(data: T): Promise<any> {
    const { bcGraphqlToken } = store.getState().company.tokens
    const config = {
      // Authorization: `Bearer  ${bcGraphqlToken}`,
      Authorization: `Bearer  ${bcGraphqlToken ?? window.STOREFRONT_GRAPHQL_TOKEN}`,
    }
    return graphqlRequest(RequestType.BCGraphql, data, config)
  },
    /* ... */
}
```

It appears to work at least now in my local. Please advise on the proper way to resolve this, thank you!

**Comment by onur-o7** [comment]
same issue here but i am using headless catalyst setup. building buyers portal with modified `b3Fetch.ts` is not a solid solution maybe a new way to be able to put allowed orgin to b2b proxy via b2badmin api could be a solution.

**Comment by bc-marco** [comment]
Hello @sunilit42 @jp06 @onur-o7 
Could you provide the following information, in order to assist you properly:
```
endpoint
```

```
payload
```

**Comment by jp06** [comment]
Hi @bc-marco, here:

**Endpoint:**
```
https://api-b2b.bigcommerce.com/api/v2/proxy
```

**Payload:**
```json
{
    "storeHash": "<redacted>",
    "method": "post",
    "url": "/v3/storefront/api-token",
    "params": {},
    "data": {
        "channel_id": 1,
        "expires_at": 1866896353,
        "allowed_cors_origins": [
            "https://<slug given by Cloudflare>.trycloudflare.com"
        ]
    }
}
```

I am tunnelling my local Stencil with Cloudflare Tunnel:
```bash
# 3016 being the non-browsersync port
cloudflared tunnel --url http://localhost:3016
```

Might be worth noting that hardcoding the actual storefront URLs gives a token. I tried on both of these variants:
- `https://<slug from store name>.mybigcommerce.com`
- `https://store-<store hash>.mybigcommerce.com`

**Comment by bc-marco** [comment]
Thanks for provide the information @jp06 

In your case that is not going to work as were accomplishing security requisites, **we are not allowed to generate api-tokens to origins that are different from those that are registered on the site**

You could update your url sites by doing an update request
```bash
curl --request PUT \
  --url 'https://api.bigcommerce.com/stores/[store_hash]/v3/channels/[channel_id]/site' \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --header 'X-Auth-Token: xxxxxxxxxxxxxxxxx' \
  --data '{"url":"string"}'
```

Then you can verify which are the registered urls on your site by doing a request to
```bash
curl --request GET \
  --url 'https://api.bigcommerce.com/stores/[store_hash]/v3/channels/[channel_id]/site' \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --header 'X-Auth-Token: xxxxxxxxxxxxxxxxx'
``` 

For more information you can check here: https://developer.bigcommerce.com/docs/rest-management/channels/site#get-a-channel-site

**Comment by sunilit42** [comment]
Hello @bc-marco 

As i see https://api-b2b.bigcommerce.com/api/v2/proxy need b2b client Id , how i can get this one? is that same as b2b api token?

**Comment by jp06** [comment]
> Hello @bc-marco
> 
> As i see https://api-b2b.bigcommerce.com/api/v2/proxy need b2b client Id , how i can get this one? is that same as b2b api token?

You can check the generated B2B Edition footer script in Script Manager for this.

**Comment by jp06** [comment]
Hi @bc-marco, understandable, that makes sense. From the docs, it seems to only allow one site URL anyway, so I probably won't touch that. Thanks for the clarification!

**Comment by sunilit42** [comment]
@bc-marco @jp06 
so what is final solution to call from locally for temp i using @jp06 way add window.STOREFRONT_GRAPHQL_API_TOKEN} and use it

**Comment by bc-marco** [comment]
> Hello @bc-marco
> 
> As i see https://api-b2b.bigcommerce.com/api/v2/proxy need b2b client Id , how i can get this one? is that same as b2b api token?

Could you show me what is the current payload of your request? That will help us to provide you better support

**Comment by jp06** [comment]
@bc-marco I think he just meant to ask what the preferred final solution is, he's currently using the workaround I did for now (he said in the Slack channel).

@sunilit42  So, to review the ways so far that I know for Buyer Portal development with Stencil storefront:
1. Tunnel local Stencil and add the header/footer scripts to theme code (in local only, don't commit) and modify Buyer Portal code to make use of `{{{ settings.storefront_api.token }}}`.
2. The setup mentioned in the documentation. Adding the header/footer scripts in Script Manager and accessing the Buyer Portal directly in the store. The documentation doesn't mention it so I'm not sure, but you may also need to remove the third-party that came along with B2B Edition setup (@bc-marco please confirm if this is the case).

It really depends on preference, if no one else tests/use the Buyer Portal in the sandbox store when you're developing, method 2 might be preferred. I use method 1 as the Buyer Portal eventually has to be tested by someone else. I find it more convenient to just have the local development scripts in my local, and I won't have to "toggle" the header and footer scripts in Script Manager to go back and forth to using local and deployed Buyer Portal (well, I know I can use a script to automate switching with the Scripts API but can't be bothered yet). You have your own circumstances so it's up to you in the end, unless maybe others can provide a better way.

**Comment by bc-victor** [comment]
@jp06  I've submitted a new feature request for this issue - specifically, we'll support the token in the handlebars page context and we'll provide better documentation for Stencil CLI users

**Comment by jp06** [comment]
Great! Trying again in local with code synced to upstream, it seems like there is no need to tunnel now?

**Comment by matteocollina** [comment]
Hi, I’m trying to run Stencil on port `3002` through an ngrok tunnel, and the B2B Buyer Portal on port `3001`.

In both `base.html` and `empty.html`, I added the following local-development setup:

```html
<script nonce="{{nonce}}">
    {{!-- Change document class from no-js to js so we can detect this in css --}}
    document.documentElement.className = document.documentElement.className.replace('no-js', 'js');
</script>

<script nonce="{{nonce}}">
    window.isLocalStencilDevelopment = /(ngrok-free.app|localhost|127\.0\.0\.1|0\.0\.0\.0)$/i.test(window.location.hostname);
    console.log('window.isLocalStencilDevelopment', window.isLocalStencilDevelopment);
    if (window.isLocalStencilDevelopment) {
        {{#if customer.id}}
        {{#contains page_type "account"}}
        var b2bHideBodyStyle = document.createElement('style');
        b2bHideBodyStyle.id = 'b2b-account-page-hide-body';
        b2bHideBodyStyle.innerHTML = 'body { display: none !important }';
        document.head.appendChild(b2bHideBodyStyle);
        {{/contains}}
        {{/if}}
    }
</script>
<script type="module">
    if (window.isLocalStencilDevelopment) {
        const RefreshRuntime = (await import('http://localhost:3001/@react-refresh')).default;
        RefreshRuntime.injectIntoGlobalHook(window);
        window.$RefreshReg$ = () => {};
        window.$RefreshSig$ = () => (type) => type;
        window.__vite_plugin_react_preamble_installed__ = true;
    }
</script>
<script type="module">
    if (window.isLocalStencilDevelopment) {
        await import('http://localhost:3001/@vite/client');
    }
</script>
```

When I open the B2B portal from Stencil, the UI renders correctly. However, when trying to log in, the GraphQL request to the ngrok Stencil URL returns `401`.

The request is sent to:

```text
https://<ngrok-subdomain>.ngrok-free.app/graphql
```

and the relevant headers look like this:

```text
authorization: Bearer
origin: https://<ngrok-subdomain>.ngrok-free.app
referer: https://<ngrok-subdomain>.ngrok-free.app/
x-sf-csrf-token: <present>
x-xsrf-token: <present>
```

The GraphQL mutation is:

```graphql
mutation Login($email: String!, $password: String!) {
  login(email: $email, password: $password) {
    result
    customer {
      entityId
      phone
      firstName
      lastName
      email
      customerGroupId
    }
  }
}
```

I also see this error in the console:

```text
installHook.js:1 Error: {'allowed_cors_origins': [ErrorDetail(string='Dati non validi', code='invalid')]}
    at b3Fetch.ts:136:21
    at async loginInfo (loginInfo.ts:58:17)
    at async init (App.tsx:203:11)
```

I tried changing the `allowed_cors_origins` array in the B2B app configuration as well, but the issue still happens.

Is there any additional configuration needed to make the B2B Buyer Portal work with a local Stencil instance exposed through ngrok, especially for the login/auth flow?
